development:
  adapter: mysql2
  database: writeapp_sinatra
  host: localhost
  username: root
  password:
  encoding: utf8
  pool: 30
production:
  adapter: mysql2
  encoding: utf8
  database: writeapp_sinatra
  username: root
  password:
  host: localhost
  pool: 30
