development:
  adapter: mysql2
  database: writeapp_sinatra
  host: localhost
  username: root
  password:
  encoding: utf8
  pool: 30
production_local:
  adapter: mysql2
  encoding: utf8
  database: writeapp_sinatra
  username: root
  password:
  host: localhost
  pool: 30
production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  pool: 30
